language: node_js
node_js:
  - 0.10
env:
  global:
    - PATH=$PWD/node_modules/.bin:$PATH
before_install:
  - npm install -g grunt-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
script:
  - grunt eslint
  - grunt karma:travis
  - protractor test/protractor-conf.js
after_script:
  - coveralls < coverage/lcov.info
